config/routes.rb
Rails.application.routes.draw do
  root 'vehicle#index'
  get 'show', action: :index, controller: 'vehicle', as: :show
  get 'show/:identifier', to: 'vehicle#show', as: :vehicle, constraint: { identifier: /\d/ }
  #post 'api/v1/gps', to: 'waypoint#create'
  get 'api/v1/waypoint/:vehicles_id', to: 'waypoint#get_last', constraint: { vehicles_id: /\d/ }
  get 'api/v1/waypoints/:vehicles_id', to: 'waypoint#get_historical', constraint: { vehicles_id: /\w\d/ }
  namespace 'api', defaults: { format: "json" } do
    namespace 'v1' do
      post 'gps', controller: 'gps', action: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicles.rb
class Vehicles < ApplicationRecord
    has_many :waypoints, dependent: :destroy
    validates :identifier, presence: true

end

app/models/waypoint.rb
class Waypoint < ApplicationRecord
    belongs_to :vehicles
    validates :latitude, presence: true
    validates :longitude, presence: true
    validates :vehicles_id, presence: true
    validates :send_at, presence: true
end

app/controllers/api/v1/gps_controller.rb
module Api
    module V1
        class GpsController < ApplicationController
            skip_before_action :verify_authenticity_token
            def create
                message = WaypointController.create_waypoint(params)
                render json:  {job: message}, status: :ok
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vehicle_controller.rb
class VehicleController < ApplicationController

  before_action :set_vehicle, only: [:show]

  def index
    @vehicles = Vehicles.all
    current_uri = request.env['PATH_INFO']
    respond_to do |format|
      format.json {
        render json: { vehicles: @vehicles, uri: current_uri }
      }
      format.html
    end
  end

  def show()
    respond_to do |format|
      if vehicle_exist
        format.json {
          render json: { vehicle: vehicle_find, status: true }
        }
        format.html {
          @vehicle = vehicle_find
          @status= true 
        }
      else
        format.json {
          render json: { status: false }
        }
        format.html
      end
    end
  end

  class << self

    def create_or_find(identifier)
      Vehicles.find_or_create_by(identifier: identifier)
    end
  end

  private

    def set_vehicle
    end

    def vehicle_exist
      Vehicles.exists?(params[:identifier])
    end

    def vehicle_find
      Vehicles.find(params[:identifier])
    end

end

app/controllers/waypoint_controller.rb
class WaypointController < ApplicationController

    def get_last
        render json: last_waypoint
    end

    def get_historical
        render json: historical_waypoints
    end

    class << self
        def create_waypoint(params)
            message = {}
            vehicle = VehicleController.create_or_find(params[:vehicle_identifier])
            if vehicle
                vehicle.update(updated_at: Time.parse(params[:sent_at]).strftime("%Y-%m-%d %H:%M:%S"))
                if create(vehicle, params)
                    message = { status: true, time: Time.parse(params[:sent_at]).strftime("%Y-%m-%d %H:%M:%S") }
                end
            end
            return message
        end
        handle_asynchronously :create_waypoint

        def create(vehicle, params)
            Waypoint.create(latitude: params[:latitude], longitude: params[:longitude], send_at: Time.parse(params[:sent_at]).strftime("%Y-%m-%d %H:%M:%S"), vehicles_id: vehicle.id)
        end
    end

    private

    def last_waypoint
        Waypoint.order(send_at: :desc).where(vehicles_id: params[:vehicles_id]).first()
    end
    
    def historical_waypoints
        Waypoint.order(send_at: :desc).where(vehicles_id: params[:vehicles_id]).all()
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicle_helper.rb
module VehicleHelper
end

app/helpers/waypoint_helper.rb
module WaypointHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackWaypointsVue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'vue_app' %>
    <link rel="stylesheet" href="https://openlayers.org/en/latest/css/ol.css" type="text/css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicle/index.html.erb

<h1>List Vehicles</h1>
<div id ="information">  
  <table>
    <tr>
      <th>Identifier</th>
      <th>Last Update</th>
      <th>Historical</th>
    </tr>
  
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.identifier %></td>
        <td>
          <% if vehicle.updated_at %>
          <%= vehicle.updated_at.strftime('%d-%m-%Y %H:%M:%S') %></td>
          <% end %>
        <td><%= button_to "Show", vehicle_path(vehicle), :method => "get", class: 'btnShow' %></td>
      </tr>
    <% end %>
  </table>
</div>
<div id="app" class="vehiclesMap">
  <vehicles :marks="<%= @vehicles.to_json %>"></vehicles>
</div>

app/views/vehicle/show.html.erb
<div id="app">
  <%= button_to "Back", show_path, :method => "get", class: 'btnBack' %>
  <% if @status %>
    <div class="title">
      <h1><%= @vehicle.identifier %></h1>
    </div>
    <historical :vehicle="<%= @vehicle.to_json%>"></historical>
  <% else %>
    <h1>This vehicle doesn't exist.</h1>
  <% end %>
</div>